### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by dfeistel3** [baymlab/wastewater_analysis#1]
not related to code, but its a bit unclear where to get the metadata.tsv from for the preprocessing step.  Any input on where this is located or how to download it from the GISAD site?

**Comment by jbaaijens** [comment]
Hi @dfeistel3, the metadata has to be downloaded from GISAID, together with the genome sequences. For GISAID you have to register before you are allowed to download the data, which is why I can't provide it here. I’ll make a note about this in the instructions.

**Comment by jbaaijens** [comment]
Once you've registered on GISAID, go to EpiCoV -> Downloads -> Download packages -> FASTA and metadata
