### ISSUE TITLE
VLQ for Nanopore sequencing data

### ISSUE THREAD

**Issue by leocaserta** [baymlab/wastewater_analysis#10]
Hello, 
I see that one of the steps requires forward and reverse fastq files, but I'm wondering if it works with single-end reads like Nanopore data 

Thank you 

Leonardo

**Comment by jbaaijens** [comment]
Hi Leonardo,

In the future we may extend to long-read data, but currently VLQ only supports paired-end data. 

I'm closing this issue for now, please feel free to reopen if you have any further questions.

Jasmijn
